import { Inter } from "next/font/google";
import "./globals.css";

import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from "sonner";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DataSync | OnBoard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Toaster position="bottom-right" richColors />

          {children}
        </ReduxProvider>

        <Script
          type="module"
          src="https://public.tableau.com/javascripts/api/tableau.embedding.3.latest.min.js"
        />
      </body>
    </html>
  );
}
