import { Inter } from "next/font/google";
import "./globals.css";

import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DataSync | OnBoard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Toaster position="bottom-right" richColors />

          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
