import SiteProvider from "@/providers/SiteProvider";

export const metadata = {
  title: "DataSync | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return <SiteProvider>{children}</SiteProvider>;
}
